services:
  mongodb:
    container_name: dd-mongo
    restart: unless-stopped
    image: mongo
    ports:
    - 27017:27017

  dd-user-service:
    container_name: dd-user-service
    restart: unless-stopped
    image: gusfringgaming/dd-user-service:latest
    ports:
    - 1927:1927
    env_file:
    - ./config/user-service.env

  dd-auth:
    container_name: dd-auth
    restart: unless-stopped
    image: gusfringgaming/dd-auth:latest
    volumes:
    - type: bind
      source: ./data/auth
      target: /usr/src/auth/data
    ports:
    - 8082:8082

  dd-client:
    container_name: dd-client
    restart: unless-stopped
    image: gusfringgaming/dd-client:latest
    volumes:
    - type: bind
      source: ./data/client
      target: /usr/src/client/data
    ports:
    - 4096:4096

  dd-gateway:
    container_name: dd-gateway
    restart: unless-stopped
    image: gusfringgaming/dd-gateway:latest
    volumes:
    - type: bind
      source: ./data/gateway
      target: /usr/src/gw/data
    ports:
    - 9000:9000