name: discdoor
services:
 
  dd-user-service:
    container_name: dd-user-service
    restart: unless-stopped
    image: gusfringgaming/dd-user-service:main
    ports:
    - 1927:1927
    env_file:
    - ./config/user-service.env

  mongodb:
    container_name: dd-mongo
    restart: unless-stopped
    image: mongo
    ports:
    - 27017:27017
